name:
  Test Cron Job
on:
  schedule:
    - cron: "*/5 * * * *"
  pull_request:
    types: [closed, assigned, opened, reopened]
    branches: ["main"]
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo Hello, world!
