name:
  Test Cron Job
on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches: ["main"]
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: cd ../../
      - name: step-2
        run: ls -a
