name:
  Test Cron Job
on:
  schedule:
    - cron: "0 */1 * * *"
  push:
    branches: ["main"]
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
