name:
  Test Cron Job
on:
  schedule:
    - cron: "* * * * *"
  push:
    branches: ["main"]
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: run
        run: ls
      - name: run-2
        run: cd ../../ && ls
      - name: run-3
        run: cd cron-job && ls
